### PR TITLE
Fix harmonizer to work in python3

### PR DESCRIPTION
**Pull request by markk**
Harmonizer() included division which produces a float in python3.
Values were therefore not valid to be passed to Transpose().

### CODE REVIEW

**Comment by stefets** [comment]
Thanks for the fix, applied in my fork today.

**Comment by stefets** [comment]
Hi @markk, 

I am following your commits and others forks to keep my mididings alive. This one give you more performance ? You had issue with the old collection ?

**Comment by markk** [comment]
Hi, no it's just that in python 3.10 Callable can no longer be referenced from collections. (A proper patch would have been to wrap the import in a try/except, but I won't be using it on python < 3.10 so I didn't bother.)

**Comment by stefets** [comment]
Upgraded to Python 3.10.3 today, good fix.  And I had to build Boost to 1.78 in the same time.

**Pull request closed without merging**
